server:
  port: 8080


spring:
  application:
    name: shoppingCartProcess

  profiles:
    active: local

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: guest
    password: welcome1
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: guest
      password: welcome1
      driver-class-name: org.postgresql.Driver
      pool-name: CAMUNDA-HIKARI-POOL
      idle-timeout: 3000
      minimum-idle: 30
      maximum-pool-size: 10
      connection-timeout: 2000
      connection-test-query: select 1
      transaction-isolation: TRANSACTION_READ_COMMITTED


camunda:
  bpm:
    enabled: true
    admin-user:
      id: demo
      password: demo
    database:
      schema-update: true
    filter:
      create: all


